# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"6\n\x0cSpeedCommand\x12\n\n\x02vx\x18\x01 \x02(\x02\x12\n\n\x02vy\x18\x02 \x01(\x02\x12\x0e\n\x06vtheta\x18\x03 \x02(\x02\"1\n\nPosCommand\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"=\n\nOdomReport\x12\r\n\x05pos_x\x18\x01 \x02(\x02\x12\r\n\x05pos_y\x18\x02 \x02(\x02\x12\x11\n\tpos_theta\x18\x03 \x02(\x02\"%\n\x03IHM\x12\x0f\n\x07tirette\x18\x01 \x02(\x08\x12\r\n\x05\x63olor\x18\x02 \x02(\x08\"+\n\x0b\x42uoyCatcher\x12\x0e\n\x06height\x18\x01 \x02(\x05\x12\x0c\n\x04grab\x18\x02 \x02(\x08\"\x18\n\tFlagServo\x12\x0b\n\x03pos\x18\x01 \x02(\x05\"\xbd\x01\n\x0bTopLevelMsg\x12\x1e\n\x05speed\x18\x01 \x01(\x0b\x32\r.SpeedCommandH\x00\x12\x1a\n\x03pos\x18\x02 \x01(\x0b\x32\x0b.PosCommandH\x00\x12\x1b\n\x04odom\x18\x03 \x01(\x0b\x32\x0b.OdomReportH\x00\x12\x13\n\x03ihm\x18\x04 \x01(\x0b\x32\x04.IHMH\x00\x12\x1c\n\x04\x62uoy\x18\x05 \x01(\x0b\x32\x0c.BuoyCatcherH\x00\x12\x1b\n\x05servo\x18\x06 \x01(\x0b\x32\n.FlagServoH\x00\x42\x05\n\x03msg')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEEDCOMMAND._serialized_start=18
  _SPEEDCOMMAND._serialized_end=72
  _POSCOMMAND._serialized_start=74
  _POSCOMMAND._serialized_end=123
  _ODOMREPORT._serialized_start=125
  _ODOMREPORT._serialized_end=186
  _IHM._serialized_start=188
  _IHM._serialized_end=225
  _BUOYCATCHER._serialized_start=227
  _BUOYCATCHER._serialized_end=270
  _FLAGSERVO._serialized_start=272
  _FLAGSERVO._serialized_end=296
  _TOPLEVELMSG._serialized_start=299
  _TOPLEVELMSG._serialized_end=488
# @@protoc_insertion_point(module_scope)
