# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_actions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_actions.proto',
  package='game_actions',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12game_actions.proto\x12\x0cgame_actions\"O\n\rset_pose_args\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\x12\x19\n\x11perform_detection\x18\x04 \x01(\x08\"\x0e\n\x0cset_pose_out\"\x0f\n\rget_pose_args\"3\n\x0cget_pose_out\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\":\n\x13overwrite_pose_args\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"\x14\n\x12overwrite_pose_out\"\x12\n\x10stop_motion_args\"\x11\n\x0fstop_motion_out\"\x15\n\x13is_motion_done_args\")\n\x12is_motion_done_out\x12\x13\n\x0bmotion_done\x18\x01 \x01(\x08\"/\n\rset_pump_args\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08\"\x0e\n\x0cset_pump_out\"C\n\x11move_stepper_args\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\x0e\n\x06target\x18\x02 \x01(\x05\x12\r\n\x05speed\x18\x03 \x01(\x02\"\x12\n\x10move_stepper_out\"4\n\x12reset_stepper_args\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"\x13\n\x11reset_stepper_out\"1\n\x0fmove_servo_args\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"\x10\n\x0emove_servo_out\"\"\n\x0fget_button_args\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\" \n\x0eget_button_out\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x1b\n\nsleep_args\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x02\"\x0b\n\tsleep_outb\x06proto3'
)




_SET_POSE_ARGS = _descriptor.Descriptor(
  name='set_pose_args',
  full_name='game_actions.set_pose_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='game_actions.set_pose_args.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='game_actions.set_pose_args.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='game_actions.set_pose_args.theta', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perform_detection', full_name='game_actions.set_pose_args.perform_detection', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=115,
)


_SET_POSE_OUT = _descriptor.Descriptor(
  name='set_pose_out',
  full_name='game_actions.set_pose_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=131,
)


_GET_POSE_ARGS = _descriptor.Descriptor(
  name='get_pose_args',
  full_name='game_actions.get_pose_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=148,
)


_GET_POSE_OUT = _descriptor.Descriptor(
  name='get_pose_out',
  full_name='game_actions.get_pose_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='game_actions.get_pose_out.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='game_actions.get_pose_out.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='game_actions.get_pose_out.theta', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=201,
)


_OVERWRITE_POSE_ARGS = _descriptor.Descriptor(
  name='overwrite_pose_args',
  full_name='game_actions.overwrite_pose_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='game_actions.overwrite_pose_args.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='game_actions.overwrite_pose_args.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='game_actions.overwrite_pose_args.theta', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=261,
)


_OVERWRITE_POSE_OUT = _descriptor.Descriptor(
  name='overwrite_pose_out',
  full_name='game_actions.overwrite_pose_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=283,
)


_STOP_MOTION_ARGS = _descriptor.Descriptor(
  name='stop_motion_args',
  full_name='game_actions.stop_motion_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=303,
)


_STOP_MOTION_OUT = _descriptor.Descriptor(
  name='stop_motion_out',
  full_name='game_actions.stop_motion_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=322,
)


_IS_MOTION_DONE_ARGS = _descriptor.Descriptor(
  name='is_motion_done_args',
  full_name='game_actions.is_motion_done_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=345,
)


_IS_MOTION_DONE_OUT = _descriptor.Descriptor(
  name='is_motion_done_out',
  full_name='game_actions.is_motion_done_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motion_done', full_name='game_actions.is_motion_done_out.motion_done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=388,
)


_SET_PUMP_ARGS = _descriptor.Descriptor(
  name='set_pump_args',
  full_name='game_actions.set_pump_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='game_actions.set_pump_args.channel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='game_actions.set_pump_args.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=437,
)


_SET_PUMP_OUT = _descriptor.Descriptor(
  name='set_pump_out',
  full_name='game_actions.set_pump_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=453,
)


_MOVE_STEPPER_ARGS = _descriptor.Descriptor(
  name='move_stepper_args',
  full_name='game_actions.move_stepper_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='game_actions.move_stepper_args.channel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='game_actions.move_stepper_args.target', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='game_actions.move_stepper_args.speed', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=522,
)


_MOVE_STEPPER_OUT = _descriptor.Descriptor(
  name='move_stepper_out',
  full_name='game_actions.move_stepper_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=542,
)


_RESET_STEPPER_ARGS = _descriptor.Descriptor(
  name='reset_stepper_args',
  full_name='game_actions.reset_stepper_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='game_actions.reset_stepper_args.channel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='game_actions.reset_stepper_args.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=596,
)


_RESET_STEPPER_OUT = _descriptor.Descriptor(
  name='reset_stepper_out',
  full_name='game_actions.reset_stepper_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=617,
)


_MOVE_SERVO_ARGS = _descriptor.Descriptor(
  name='move_servo_args',
  full_name='game_actions.move_servo_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='game_actions.move_servo_args.channel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='game_actions.move_servo_args.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=668,
)


_MOVE_SERVO_OUT = _descriptor.Descriptor(
  name='move_servo_out',
  full_name='game_actions.move_servo_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=686,
)


_GET_BUTTON_ARGS = _descriptor.Descriptor(
  name='get_button_args',
  full_name='game_actions.get_button_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='game_actions.get_button_args.channel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=722,
)


_GET_BUTTON_OUT = _descriptor.Descriptor(
  name='get_button_out',
  full_name='game_actions.get_button_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='game_actions.get_button_out.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=756,
)


_SLEEP_ARGS = _descriptor.Descriptor(
  name='sleep_args',
  full_name='game_actions.sleep_args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay', full_name='game_actions.sleep_args.delay', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=758,
  serialized_end=785,
)


_SLEEP_OUT = _descriptor.Descriptor(
  name='sleep_out',
  full_name='game_actions.sleep_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=798,
)

DESCRIPTOR.message_types_by_name['set_pose_args'] = _SET_POSE_ARGS
DESCRIPTOR.message_types_by_name['set_pose_out'] = _SET_POSE_OUT
DESCRIPTOR.message_types_by_name['get_pose_args'] = _GET_POSE_ARGS
DESCRIPTOR.message_types_by_name['get_pose_out'] = _GET_POSE_OUT
DESCRIPTOR.message_types_by_name['overwrite_pose_args'] = _OVERWRITE_POSE_ARGS
DESCRIPTOR.message_types_by_name['overwrite_pose_out'] = _OVERWRITE_POSE_OUT
DESCRIPTOR.message_types_by_name['stop_motion_args'] = _STOP_MOTION_ARGS
DESCRIPTOR.message_types_by_name['stop_motion_out'] = _STOP_MOTION_OUT
DESCRIPTOR.message_types_by_name['is_motion_done_args'] = _IS_MOTION_DONE_ARGS
DESCRIPTOR.message_types_by_name['is_motion_done_out'] = _IS_MOTION_DONE_OUT
DESCRIPTOR.message_types_by_name['set_pump_args'] = _SET_PUMP_ARGS
DESCRIPTOR.message_types_by_name['set_pump_out'] = _SET_PUMP_OUT
DESCRIPTOR.message_types_by_name['move_stepper_args'] = _MOVE_STEPPER_ARGS
DESCRIPTOR.message_types_by_name['move_stepper_out'] = _MOVE_STEPPER_OUT
DESCRIPTOR.message_types_by_name['reset_stepper_args'] = _RESET_STEPPER_ARGS
DESCRIPTOR.message_types_by_name['reset_stepper_out'] = _RESET_STEPPER_OUT
DESCRIPTOR.message_types_by_name['move_servo_args'] = _MOVE_SERVO_ARGS
DESCRIPTOR.message_types_by_name['move_servo_out'] = _MOVE_SERVO_OUT
DESCRIPTOR.message_types_by_name['get_button_args'] = _GET_BUTTON_ARGS
DESCRIPTOR.message_types_by_name['get_button_out'] = _GET_BUTTON_OUT
DESCRIPTOR.message_types_by_name['sleep_args'] = _SLEEP_ARGS
DESCRIPTOR.message_types_by_name['sleep_out'] = _SLEEP_OUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

set_pose_args = _reflection.GeneratedProtocolMessageType('set_pose_args', (_message.Message,), {
  'DESCRIPTOR' : _SET_POSE_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.set_pose_args)
  })
_sym_db.RegisterMessage(set_pose_args)

set_pose_out = _reflection.GeneratedProtocolMessageType('set_pose_out', (_message.Message,), {
  'DESCRIPTOR' : _SET_POSE_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.set_pose_out)
  })
_sym_db.RegisterMessage(set_pose_out)

get_pose_args = _reflection.GeneratedProtocolMessageType('get_pose_args', (_message.Message,), {
  'DESCRIPTOR' : _GET_POSE_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.get_pose_args)
  })
_sym_db.RegisterMessage(get_pose_args)

get_pose_out = _reflection.GeneratedProtocolMessageType('get_pose_out', (_message.Message,), {
  'DESCRIPTOR' : _GET_POSE_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.get_pose_out)
  })
_sym_db.RegisterMessage(get_pose_out)

overwrite_pose_args = _reflection.GeneratedProtocolMessageType('overwrite_pose_args', (_message.Message,), {
  'DESCRIPTOR' : _OVERWRITE_POSE_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.overwrite_pose_args)
  })
_sym_db.RegisterMessage(overwrite_pose_args)

overwrite_pose_out = _reflection.GeneratedProtocolMessageType('overwrite_pose_out', (_message.Message,), {
  'DESCRIPTOR' : _OVERWRITE_POSE_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.overwrite_pose_out)
  })
_sym_db.RegisterMessage(overwrite_pose_out)

stop_motion_args = _reflection.GeneratedProtocolMessageType('stop_motion_args', (_message.Message,), {
  'DESCRIPTOR' : _STOP_MOTION_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.stop_motion_args)
  })
_sym_db.RegisterMessage(stop_motion_args)

stop_motion_out = _reflection.GeneratedProtocolMessageType('stop_motion_out', (_message.Message,), {
  'DESCRIPTOR' : _STOP_MOTION_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.stop_motion_out)
  })
_sym_db.RegisterMessage(stop_motion_out)

is_motion_done_args = _reflection.GeneratedProtocolMessageType('is_motion_done_args', (_message.Message,), {
  'DESCRIPTOR' : _IS_MOTION_DONE_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.is_motion_done_args)
  })
_sym_db.RegisterMessage(is_motion_done_args)

is_motion_done_out = _reflection.GeneratedProtocolMessageType('is_motion_done_out', (_message.Message,), {
  'DESCRIPTOR' : _IS_MOTION_DONE_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.is_motion_done_out)
  })
_sym_db.RegisterMessage(is_motion_done_out)

set_pump_args = _reflection.GeneratedProtocolMessageType('set_pump_args', (_message.Message,), {
  'DESCRIPTOR' : _SET_PUMP_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.set_pump_args)
  })
_sym_db.RegisterMessage(set_pump_args)

set_pump_out = _reflection.GeneratedProtocolMessageType('set_pump_out', (_message.Message,), {
  'DESCRIPTOR' : _SET_PUMP_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.set_pump_out)
  })
_sym_db.RegisterMessage(set_pump_out)

move_stepper_args = _reflection.GeneratedProtocolMessageType('move_stepper_args', (_message.Message,), {
  'DESCRIPTOR' : _MOVE_STEPPER_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.move_stepper_args)
  })
_sym_db.RegisterMessage(move_stepper_args)

move_stepper_out = _reflection.GeneratedProtocolMessageType('move_stepper_out', (_message.Message,), {
  'DESCRIPTOR' : _MOVE_STEPPER_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.move_stepper_out)
  })
_sym_db.RegisterMessage(move_stepper_out)

reset_stepper_args = _reflection.GeneratedProtocolMessageType('reset_stepper_args', (_message.Message,), {
  'DESCRIPTOR' : _RESET_STEPPER_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.reset_stepper_args)
  })
_sym_db.RegisterMessage(reset_stepper_args)

reset_stepper_out = _reflection.GeneratedProtocolMessageType('reset_stepper_out', (_message.Message,), {
  'DESCRIPTOR' : _RESET_STEPPER_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.reset_stepper_out)
  })
_sym_db.RegisterMessage(reset_stepper_out)

move_servo_args = _reflection.GeneratedProtocolMessageType('move_servo_args', (_message.Message,), {
  'DESCRIPTOR' : _MOVE_SERVO_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.move_servo_args)
  })
_sym_db.RegisterMessage(move_servo_args)

move_servo_out = _reflection.GeneratedProtocolMessageType('move_servo_out', (_message.Message,), {
  'DESCRIPTOR' : _MOVE_SERVO_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.move_servo_out)
  })
_sym_db.RegisterMessage(move_servo_out)

get_button_args = _reflection.GeneratedProtocolMessageType('get_button_args', (_message.Message,), {
  'DESCRIPTOR' : _GET_BUTTON_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.get_button_args)
  })
_sym_db.RegisterMessage(get_button_args)

get_button_out = _reflection.GeneratedProtocolMessageType('get_button_out', (_message.Message,), {
  'DESCRIPTOR' : _GET_BUTTON_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.get_button_out)
  })
_sym_db.RegisterMessage(get_button_out)

sleep_args = _reflection.GeneratedProtocolMessageType('sleep_args', (_message.Message,), {
  'DESCRIPTOR' : _SLEEP_ARGS,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.sleep_args)
  })
_sym_db.RegisterMessage(sleep_args)

sleep_out = _reflection.GeneratedProtocolMessageType('sleep_out', (_message.Message,), {
  'DESCRIPTOR' : _SLEEP_OUT,
  '__module__' : 'game_actions_pb2'
  # @@protoc_insertion_point(class_scope:game_actions.sleep_out)
  })
_sym_db.RegisterMessage(sleep_out)


# @@protoc_insertion_point(module_scope)
